services:
  nginx:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
      - php

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secred
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
    entrypoint: ["php", "/var/www/html/artisan"]

  composer:
    image: composer:2
    volumes:
      - ./src:/app
    working_dir: /app
    entrypoint: ["composer"]
